apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: ml-pipeline-
spec:
  entrypoint: ml-pipeline
  serviceAccountName: argo

  templates:

    # ----------------------------
    # ENTRYPOINT DAG
    # ----------------------------
    - name: ml-pipeline
      dag:
        tasks:
          # EDA
          - name: eda
            template: python-task
            arguments:
              parameters:
                - name: script
                  value: /app/eda.py

          # Preprocessing
          - name: preprocessing
            template: python-task
            arguments:
              parameters:
                - name: script
                  value: /app/preprocessing.py
            dependencies: [eda]

          # Training
          - name: training
            template: python-task
            arguments:
              parameters:
                - name: script
                  value: /app/train.py
                - name: preprocessing_run_id
                  value: "{{tasks.preprocessing.outputs.parameters.run_id}}"
            dependencies: [preprocessing]

          # Evaluation
          - name: evaluation
            template: python-task
            arguments:
              parameters:
                - name: script
                  value: /app/evaluation.py
                - name: training_run_id
                  value: "{{tasks.training.outputs.parameters.run_id}}"
            dependencies: [training]

    # ----------------------------
    # PYTHON TASK TEMPLATE
    # ----------------------------
    - name: python-task
      inputs:
        parameters:
          - name: script
          - name: preprocessing_run_id
            default: ""
          - name: training_run_id
            default: ""
      outputs:
        parameters:
          - name: run_id
            valueFrom:
              path: /tmp/run_id.txt
      container:
        image: ghcr.io/marius2311/python-for-ml:1.0
        command: ["python"]
        args:
          - "{{inputs.parameters.script}}"
          - "--preprocessing-run-id"
          - "{{inputs.parameters.preprocessing_run_id}}"
          - "--training-run-id"
          - "{{inputs.parameters.training_run_id}}"
